services:
  emsbus:
    image: emsbus-2.0.11
    container_name: emsbus
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 2301:2301
      - 2389:2389
    networks:
      - network_ems_bus
    stdin_open: true
    tty: true
    volumes:
      - ./config:/app/priv/conf

networks:
  network_ems_bus:
    driver: bridge