- name: Provisionar pacotes comuns
  import_playbook: common/playbook-comuns.yml

- name: Provisionar Docker
  import_playbook: common/playbook-docker.yml

- name: Provisionar Erlang
  import_playbook: common/playbook-erlang.yml
