---
- name: Instala Erlang
  hosts: all
  become: true
  vars:
    erlang_packages:
      - build-essential
      - ldap-utils
      - erlang-asn1
      - erlang-base
      - erlang-crypto
      - erlang-dev
      - erlang-dialyzer
      - erlang-diameter
      - erlang-edoc
      - erlang-eunit
      - erlang-ftp
      - erlang-inets
      - erlang-jiffy
      - erlang-mnesia
      - erlang-odbc
      - erlang-proper
      - erlang-public-key
      - erlang-reltool
      - erlang-runtime-tools
      - erlang-snmp
      - erlang-ssl
      - erlang-syntax-tools
      - erlang-tftp
      - erlang-tools
      - erlang-wx
      - erlang-xmerl

  tasks:
    - name: Coletar fatos manualmente
      ansible.builtin.setup:

    - name: Garante que o sistema está atualizado
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Instala os pacotes Erlang
      ansible.builtin.apt:
        name: "{{ erlang_packages }}"
        state: present
