---
- name: Provisionamento básico das VMs
  hosts: all
  become: true
  tasks:
    - name: Atualizar cache de pacotes
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Instalar pacotes básicos
      ansible.builtin.apt:
        name:
          - git
          - vim
          - curl
          - wget
          - unzip
          - lsof
          - bash-completion
          - tree
        state: present

    - name: Garantir que o locale pt_BR.UTF-8 esteja gerado (Debian/Ubuntu)
      community.general.locale_gen:
        name: pt_BR.UTF-8
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: Configurar timezone para America/Sao_Paulo
      community.general.timezone:
        name: America/Sao_Paulo
